package dev.denismasterherobrine.densityfunctioncompiler.compiler.runtime;

/**
 * Tiny static helpers called from generated bytecode. Kept in their own class so the
 * codegen can refer to them through a stable internal name without leaking the rest of
 * the compiler implementation onto the generated method's call graph (which would push
 * past HotSpot's inlining budget for very large IR trees).
 *
 * <p>Each helper here is short and pure — HotSpot will trivially inline them at the call
 * site once the generated method itself crosses the inlining threshold.
 */
public final class Runtime {
    private Runtime() {}

    /** {@code DensityFunctions.Mapped.Type.SQUEEZE}. */
    public static double squeeze(double x) {
        double c = x < -1.0 ? -1.0 : (x > 1.0 ? 1.0 : x);
        return c / 2.0 - c * c * c / 24.0;
    }

    /**
     * {@code WeirdScaledSampler}'s rarity mapping. {@code ordinal} is the
     * {@code DensityFunctions.WeirdScaledSampler.RarityValueMapper} ordinal
     * (0 = TYPE1 / 3D, 1 = TYPE2 / 2D). Reimplemented here because the vanilla
     * {@code QuantizedSpaghettiRarity} class is package-private — duplicating these tiny
     * tables avoids depending on access transformers.
     */
    public static double weirdRarity(double v, int ordinal) {
        return ordinal == 0 ? rarity3D(v) : rarity2D(v);
    }

    private static double rarity3D(double p) {
        if (p < -0.5) return 0.75;
        if (p < 0.0)  return 1.0;
        return p < 0.5 ? 1.5 : 2.0;
    }

    private static double rarity2D(double p) {
        if (p < -0.75) return 0.5;
        if (p < -0.5)  return 0.75;
        if (p <  0.5)  return 1.0;
        return p < 0.75 ? 2.0 : 3.0;
    }
}

