package dev.denismasterherobrine.densityfunctioncompiler.compiler.codegen;

import net.minecraft.util.KeyDispatchDataCodec;
import net.minecraft.world.level.levelgen.DensityFunction;
import net.minecraft.world.level.levelgen.synth.NormalNoise;

import java.lang.invoke.MethodHandle;

/**
 * Abstract base for every runtime-compiled DensityFunction.
 *
 * <p>Subclasses are generated via ASM as <em>hidden classes</em> rooted at this class
 * (using {@link java.lang.invoke.MethodHandles.Lookup#defineHiddenClass}). They override
 * exactly {@link #compute(DensityFunction.FunctionContext)}, {@link #fillArray(double[],
 * DensityFunction.ContextProvider)} and the bounds methods using straight-line bytecode.
 *
 * <p>The {@link #constants}, {@link #noises}, {@link #splines} and {@link #externs}
 * arrays are the generated class's "constant pool" — every reference to a non-trivial
 * value (a noise sampler, a spline coefficient block, an opaque mod-provided child
 * DensityFunction) is fetched through {@code GETFIELD} on these instance fields, indexed
 * by the slot the {@link ConstantPool} assigned during compilation.
 *
 * <p>Keeping these as <em>instance</em> fields (rather than static finals) lets
 * {@link #mapAll(DensityFunction.Visitor)} produce a fresh instance with rebound externs
 * without recompiling — the bytecode and IR live on the class, the bindings live on the
 * instance.
 */
public abstract class CompiledDensityFunction implements DensityFunction {

    /** Plain double constants pulled out of the IR (literals, spline coefficients, etc.). */
    protected final double[] constants;

    /** Noise samplers captured by identity from the source DensityFunction tree. */
    protected final NormalNoise[] noises;

    /**
     * Spline coefficient blocks. Each entry is a flattened multipoint spline state
     * referenced by inlined branch sequences in the generated bytecode. May be {@code null}
     * for arithmetic-only compiled functions.
     */
    protected final Object[] splines;

    /**
     * Opaque DensityFunctions whose internals we do not (or cannot) inline:
     * mod-provided implementations, {@link net.minecraft.world.level.levelgen.DensityFunctions.Marker}
     * wrappers (preserved for {@code NoiseChunk} to swap with cell caches), Beardifier
     * placeholders, etc.
     */
    protected final DensityFunction[] externs;

    /** Cached interval-arithmetic bounds. */
    protected final double minValue;
    protected final double maxValue;

    /**
     * MethodHandles for the helper methods the {@link Codegen} extracted into
     * separate {@code helper$N} static methods on the generated class. Indexed
     * by helper id; {@code length == 0} when the function fit a single method.
     *
     * <p>Helper dispatch goes through these handles rather than {@code INVOKESTATIC}
     * because hidden classes are forbidden from referring to themselves
     * symbolically — the JVM rejects {@code defineHiddenClass} when the constant
     * pool contains a CONSTANT_Class_info referencing the hidden class's own name.
     * Holding the handles in an instance field, looked up after define via the
     * lookup returned by {@code defineHiddenClass}, sidesteps that completely
     * (handles refer to the {@link Class} object directly, no symbolic name).
     *
     * <p>Each handle has type {@code (CompiledDensityFunction, FunctionContext)D}
     * — using the supertype rather than the hidden subclass keeps the generated
     * call-site descriptors self-reference-free as well.
     */
    protected final MethodHandle[] helperHandles;

    /**
     * MethodHandle bound to the generated subclass's constructor, used by
     * {@link #rebind(NormalNoise[], DensityFunction[])} to allocate fresh
     * instances when {@link #mapAll(DensityFunction.Visitor)} produces remapped
     * externs (e.g. a {@code NoiseChunk} swapping an inner {@code Marker} with
     * its cell-cache wrapper).
     *
     * <p>Has the post-{@code asType} signature
     * {@code (double[], NormalNoise[], Object[], DensityFunction[], double,
     * double, MethodHandle[], MethodHandle) -> CompiledDensityFunction}, so
     * {@code invokeExact} just works without further boxing or casting. The
     * trailing {@code MethodHandle} arg is the constructor MH itself, threaded
     * through so the new instance can rebind again later.
     *
     * <p>Storing the MH on the instance (rather than a static field on the
     * generated class) preserves hidden-class GC: when no compiled instance
     * survives, both the MH and the generated class become reclaimable, which
     * is what we want across {@code /reload}.
     */
    protected final MethodHandle constructorMH;

    protected CompiledDensityFunction(
            double[] constants,
            NormalNoise[] noises,
            Object[] splines,
            DensityFunction[] externs,
            double minValue,
            double maxValue,
            MethodHandle[] helperHandles,
            MethodHandle constructorMH) {
        this.constants = constants;
        this.noises = noises;
        this.splines = splines;
        this.externs = externs;
        this.minValue = minValue;
        this.maxValue = maxValue;
        this.helperHandles = helperHandles;
        this.constructorMH = constructorMH;
    }

    @Override
    public final double minValue() {
        return this.minValue;
    }

    @Override
    public final double maxValue() {
        return this.maxValue;
    }

    /**
     * Delegate to {@link DensityFunction.ContextProvider#fillAllDirectly}, matching
     * vanilla {@code SimpleFunction#fillArray} semantics. The provider knows the
     * iteration pattern (cell shape, prefetch strategy) and can issue {@code compute(...)}
     * in the most cache-friendly order it has — for {@code NoiseChunk} that's the
     * cell-major iteration over the chunk slice, which both fits in L1 and lets HotSpot
     * inline our generated {@code compute} into the per-cell hot loop.
     *
     * <p>Generated subclasses are free to override {@code fillArray} with a hand-rolled
     * vectorised body (see the {@code fillarray} milestone), but in practice the inlined
     * {@code compute} call HotSpot produces is already excellent.
     */
    @Override
    public void fillArray(double[] out, DensityFunction.ContextProvider provider) {
        provider.fillAllDirectly(out, this);
    }

    /**
     * Per-instance "rebind" hook called by {@link #mapAll(DensityFunction.Visitor)}
     * when the visitor remapped at least one extern (e.g. a {@code NoiseChunk}
     * swapping an inner {@code Marker} with its cell-cache wrapper, or
     * {@code Beardifier}/{@code BlendAlpha}/{@code BlendOffset} placeholders
     * being replaced with the per-chunk implementation).
     *
     * <p>This is critical for both correctness and performance:
     * <ul>
     *   <li>Marker swaps are how {@code NoiseChunk} installs cell caches,
     *       cell-corner interpolators, 2D caches, etc. Vanilla noise routers
     *       are calibrated against the interpolator approximation, so
     *       evaluating noise per-block instead of per-cell-corner produces
     *       wildly different (mostly negative) densities — the world ends up
     *       being all lava/ocean instead of recognisable terrain.</li>
     *   <li>Inner {@code CacheOnce}/{@code FlatCache}/{@code Cache2D} cuts
     *       worldgen runtime by 1-3 orders of magnitude on typical routers.</li>
     * </ul>
     *
     * <p>Implementation: hidden classes can't emit {@code NEW SelfClass} so
     * we can't generate a typed constructor invoke in the subclass body.
     * Instead we materialise a {@link MethodHandle} bound to the subclass's
     * constructor right after {@code defineHiddenClass} returns, store it on
     * the instance (see {@link #constructorMH}), and call it via
     * {@code invokeExact} from this base-class method. The MH was
     * {@link MethodHandle#asType(java.lang.invoke.MethodType) asType}'d to
     * return {@code CompiledDensityFunction}, so the call site has no
     * self-reference either.
     */
    protected final CompiledDensityFunction rebind(NormalNoise[] visitedNoises,
                                                   DensityFunction[] visitedExterns) {
        if (constructorMH == null) {
            // Defensive: should never happen for properly-constructed compiled
            // instances. If somebody handcrafts a CompiledDensityFunction
            // without a constructor MH (e.g. a test stub) just degrade to
            // identity rebind.
            return this;
        }
        try {
            return (CompiledDensityFunction) constructorMH.invokeExact(
                    constants, visitedNoises, splines, visitedExterns,
                    minValue, maxValue, helperHandles, constructorMH);
        } catch (Throwable t) {
            throw new RuntimeException(
                    "CompiledDensityFunction.rebind failed for "
                            + this.getClass().getName(), t);
        }
    }

    @Override
    public DensityFunction mapAll(DensityFunction.Visitor visitor) {
        // Allow other mods' visitors to intercept this whole compiled function first
        // (matches Marker / TwoArgumentSimpleFunction.mapAll semantics).
        boolean changed = false;

        DensityFunction[] mappedExterns = this.externs;
        if (this.externs.length > 0) {
            mappedExterns = new DensityFunction[this.externs.length];
            for (int i = 0; i < this.externs.length; i++) {
                DensityFunction mapped = this.externs[i].mapAll(visitor);
                mappedExterns[i] = mapped;
                if (mapped != this.externs[i]) {
                    changed = true;
                }
            }
        }

        NormalNoise[] mappedNoises = this.noises;
        // We don't currently rebuild NoiseHolder objects through the visitor here; the
        // CompilingVisitor passes through visitNoise unchanged and noise instances are
        // captured by identity. Mods overriding visitNoise should remap at the source
        // DensityFunction layer, before our compiler captures references.

        DensityFunction rebound = changed ? this.rebind(mappedNoises, mappedExterns) : this;
        return visitor.apply(rebound);
    }

    @Override
    public KeyDispatchDataCodec<? extends DensityFunction> codec() {
        // Compiled functions live only in-memory; serialising a noise router back to JSON
        // after compilation would lose information anyway. If anything tries to round-trip
        // us through codecs, fail loudly rather than corrupting data.
        throw new UnsupportedOperationException(
                "CompiledDensityFunction is not serialisable (instance class: " + this.getClass().getName() + ")");
    }
}
