package dev.denismasterherobrine.densityfunctioncompiler.cache;

import dev.denismasterherobrine.densityfunctioncompiler.config.DfcConfig;
import net.minecraft.world.level.levelgen.DensityFunction;

/**
 * Optional fast path for {@code compute} on chunk cache wrappers, called from
 * generated bytecode (see {@code Codegen#emitInvoke}).
 */
public final class DfcCacheFastPath {

    /**
     * Sentinel for "use slow {@link DensityFunction#compute}" — same trick as a miss bit pattern.
     */
    public static final long MISS_BITS = 0x7ff8000000000001L; // non-canonical quiet NaN

    public static final double CACHE_MISS = Double.longBitsToDouble(MISS_BITS);

    private DfcCacheFastPath() {}

    public static double tryWrapperDirectRead(DensityFunction extern, DensityFunction.FunctionContext context) {
        if (!DfcConfig.cacheWrapperDirectRead()) {
            return CACHE_MISS;
        }
        if (extern instanceof DfcCellCacheAccess acc) {
            return acc.dfc$tryDirectRead(context);
        }
        return CACHE_MISS;
    }

    /**
     * Marker call sites flagged at compile time for NoiseChunk cache wrappers: try
     * {@link DfcCellCacheAccess#dfc$tryDirectRead} before {@link DensityFunction#compute}.
     */
    public static double computeWithOptionalDirectRead(
            DensityFunction extern, DensityFunction.FunctionContext context) {
        if (DfcConfig.cacheWrapperDirectRead() && extern instanceof DfcCellCacheAccess acc) {
            double v = acc.dfc$tryDirectRead(context);
            if (Double.doubleToRawLongBits(v) != MISS_BITS) {
                return v;
            }
        }
        return extern.compute(context);
    }
}
